### ISSUE TITLE
How to use ros::Time::now for os_cloud_node/points?

### ISSUE THREAD

**Issue by JACKLiuDay** [fada-catec/ouster_ros#1]
Hi, thank you for sharing your ouster_ros project. 
I am using my ouster which version is OS-0-64-Gen2. While the points time stamp is not ros type. So I can not use it with my imu. So I want to change the os_cloud_node/points time stamp to ros time. Could you give some advice? I don't know where to change the code in the ouster_ros file. 
Thanks.

**Comment by rcabg** [comment]
Hello @JACKLiuDay 

Thanks for commenting.

Regardless of the timestamp mode used, all the stamps published in their corresponding topic are ROS typed. Can you share an example of what you are dealing with? A screenshot may help.

Thanks!

**Comment by JACKLiuDay** [comment]
> Hello @JACKLiuDay
> 
> Thanks for commenting.
> 
> Regardless of the timestamp mode used, all the stamps published in their corresponding topic are ROS typed. Can you share an example of what you are dealing with? A screenshot may help.
> 
> Thanks!

![image](https://user-images.githubusercontent.com/30967867/205526896-1df3616f-4545-4c82-b2bc-cab2e366ca2b.png)
This is the data I print by transforming imu time and ouster data time to seconds.
I just found the reason. My ouster-ros driver is old. And it does not support ros timestamp data. I found the new version driver can solve my problem. Thank you.
